arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
name: Spotweb
version: dev
slug: spotweb
description: Spotweb is a decentralized usenet community based on the Spotnet protocol.
url: https://github.com/woutercoppens/hassio-addons/spotweb
init: false
ingress: true
ingress_port: 8099
panel_icon: mdi:chart-timeline
panel_title: Spotweb
map:
  - ssl
  - config:rw
  - backup:rw
options:
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
ports:
  80/tcp: null
ports_description:
  80/tcp: Not required for Ingress
schema:
  remote_mysql_host: str?
  remote_mysql_database: str?
  remote_mysql_username: str?
  remote_mysql_password: password?
  remote_mysql_port: int?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  certfile: str
  keyfile: str
  ssl: bool
services: 
  - mysql:want
startup: services
# webui: [PROTO:ssl]://[HOST]:[PORT:80]
hassio_api: true