arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
name: Spotweb
version: 0.0.1
slug: spotweb_docker
description: Spotweb is a decentralized usenet community based on the Spotnet protocol.
url: https://github.com/woutercoppens/hassio-addons/spotweb
startup: services
ingress: true
ingress_port: 8999
ingress_stream: true
panel_icon: mdi:chart-timeline
panel_title: Spotweb  
map:
  - config
  - ssl
options:
  plugins: []
  env_vars: []
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
ports:
  80/tcp: null
ports_description:
  80/tcp: Not required for Ingress
schema:
  remote_mysql_host: str
  remote_mysql_database: str
  remote_mysql_username: str
  remote_mysql_password: password
  remote_mysql_port: int
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  certfile: str
  keyfile: str
  ssl: bool
  env_vars:
